# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-11 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=20)),
                ('travel', models.CharField(max_length=20)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'travel',
            },
        ),
    ]
